services:
  web:
    build: .
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      - ./temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock #remove if hosting
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
    env_file:
      - .env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  runner:
    build:
      context: ./runner
    container_name: runner_service
    volumes:
      - ./temp:/app/temp
    stdin_open: true
    tty: true



volumes:
  postgres_data: